version: '2'

services: 
  node1:
    build: .
    command: /bin/bash
    tty: true
    networks:
        app_net:
            ipv4_address: 172.16.238.2

  node2:
    build: .
    command: /bin/bash
    tty: true
    networks:
        app_net:
            ipv4_address: 172.16.238.21

  node3:
    build: .
    command: /bin/bash
    tty: true
    networks:
        app_net:
            ipv4_address: 172.16.238.22

  node4:
    build: .
    command: /bin/bash
    tty: true
    networks:
        app_net:
            ipv4_address: 172.16.238.23

  node5:
    build: .
    command: /bin/bash
    tty: true
    networks:
        app_net:
            ipv4_address: 172.16.238.24

networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.16.238.0/24
         gateway: 172.16.238.1
